services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=''
      - DB_NAME=entretien
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: entretien
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
